#auto: true

# markdown的解析器
markdown: kramdown

# 代码高亮
pygments: true
# 分页设置
#paginate: 8
# 链接样式
permalink: /:title/


# title: NingG.github.com
title: ningg.top

# page中head部分的meta元素
keywords: keywords
description: NingG's Blog

# url: http://ningg.github.com
url: http://ningg.top

# feed: /atom.xml
# atom_path : /atom.xml

# author_info: <a href="http://ningg.github.com/">NingG</a>
author_info: <a href="http://ningg.top/">NingG</a>
